#!/usr/bin/perl -w
# FROM
# http://perlsoflondon.pbwiki.com/play%20with%20filehandles


#Now change it to pipe the outut through the sort -u command
# (which itself prints to STDOUT):
#
#open (LSINPUT, "ls -l |") or die "Cant do it $!\n";
#open (SORTOUT "| sort -u") or die "Cant do it $!\n";
#
#while (my $line = <LSINPUT>) {
#    print SORTOUT "I GOT $line";
#}
#
#close LSINPUT;
#close SORTOUT;
#exit;

# This model can potentially be used with the fasta program ?
my $seq_query = 
    ">1\n".
    "TGTTGGGGACTTGTTCTCAAATGCTAAGAATTAAGAACAAGGCAACATAAAATGTTAAAT".
    "ATTAAAGCCCTTCGCCCGCCGAAGCATTATTTCCTCAAGGATTTAATGAACTTCGGCGGG".
    "CGAAGGTTAGAAACGATGCAATTACGAAGGTTGAGTCTTCGTAATTGAACTCTCAAAGAT".
    "TATATAAAACAATGCGAAACATGAAACATTAAAGACAAGTAAATTATAAGTAAACGACAT".
    "TATTTTTATATTATGTAAACTTGATGTATCCAAATATTAAATACATTTATACCTCTGCCT".
    "TGGCAAAGAATAATTTCCGAGTGATGCGATTGAAATTACAGGGATGTGTGAACAGTAAAG".
    "GAATACTGTTCACTATTTATAGGCACAGGACACAACCTGTGAGGAATTACAATCATGCCC".
    "CTCATAAAAGTTTACAACATTGACTCAGACCTTTATGGGCTAAAAAGTCATTCTATCTTT".
    "AAGTCGGTTCGCCCCTTCATCTTCGGATATGTTGCAATACCGAAGCTTCATGAATGGTGC".
    "CTTCGGCGTCACGTATGAGCAGCTTCAGCCGAAGCTGTTTCTTTCTACAGGACCTTCGGC".
    "GACGAAGCATGGTCCCAACA\n".
    ">2\n".
    "TGTCGGGGACCATAATTAGGGGTACCCTCAAGACGCCTAATTCTCAGTTGGTAACCCCCA".
    "TCAGCATAAAGCTGCAAAGGCCTGATGGGTACGATTAAGTCAGGGATCAGTCCACACGAG".
    "TGACTCGATCACGCTTCACCCGAGCCTAGCCTCGGCCAAGGGCAGCCGACCTCGAGAGAC".
    "TTCCGTCTCGCCCGAGGCCCCCCTTTTTACGGCGGACACATCACCGGCTCGCCCGAGGCC".
    "TTGGCTTCGCTCAGAAGCGACCCTGACTAAATCGCCACACCGACTGACCGAGTTGCAGGA".
    "GCATTTAACGCAAAGAGTGAGTCAGACATACAGTCAGGCCTTGCCAAAGGCGCCACGGCG".
    "AACTCCGCTCCGCCCGACCCCAGGGCTCGGACTCGGGCTAAGACCCGGAAGACGGCGAAC".
    "TCCGCTCCGCCCGACCCCAGGGCTCGGCCTCGGGCTAAGACCCGGAAGACGGCGAACTTC".
    "GCTCCGCCCGACCCCAGGGCTCGGACTCGGGCTAAGACCCGGAAGACGGCGAACTCCGCT".
    "CCGCCCGACCCCAGGGCTCGGACTCGGGCTAAGACCCGGAAGACGGCGAACTCCGCTCCG".
    "CCCGACCCCAGGGCTCGGACTCGGGCTAAGACCCGGAAGACGGCGAACTCCGCTCCGCCC".
    "GACCCCAGGGCTCGGACTCGGGCTAAGACCCGGAAGACGGCGAACTCCGCTCCGCCCGAC".
    "CCCAGGGCTCGGACTCGGGCTAAGACCCGGAAGACGACGAAACTCCGCCTCGCCCGACCC".
    "CAGGGCTCGGACTCCGCCCTGGCCTCGGCCAAACGACCTCCGCCTCGCCCGACCCCATGG".
    "CTCGGACTCGGCCTCGGCAACAGAAGACAGACTCAACCTCGGCTTCGGAGGAGCCCCCAC".
    "GTCACCTCGCCTAGGGCACAGACCCGCCACGTCAACAGGAAGCGTCATCATCGTCCTACC".
    "CCGAATCGACTCGGGTCACGGAGAACAAGACCGGCGTCCCATCCGGCCAGCTCCGCCTGA".
    "TGGGCAATGATGGCGCTCCACAAGCTCTGTGACGACGGCGGCCCCCAGCTCTCTTACGGA".
    "AGCAGGGCGACGTCAGCAAGGACTCGACCGCTCCAACAGCTGTCCCTCCGCCAGGCTCCG".
    "TCGCACCTCCGACAGCCACGACATCACGCCAGCAAGGTGCCAAGACCTCTCCGGCTGCCA".
    "CATTGGCATGTACCTAGGGCGCTAGCTCTCTCTCCGCTAGACACGTAGCACTCTGCTACA".
    "CCCCCCATTGTACACCTGGATCCTCTCCTTACGACTATAAAAGGGAGGACCAGGGCCTTC".
    "TTAGAGAAGGTTGGCCGCGCGGGACCGAGGACGGGACAGGCACTCTCTTGGGGCCGCTCG".
    "CTTCCCTCACCCGCGTGGACGCTTGTAACCCCCCTACTGCAATCGCACCCGACCTGGGCG".
    "CGGGACGAACACGAAGGCCGCGGGACTTCCACCTCTCTCACGCTAGACTCCGGCCACCTC".
    "GCCTCTCCCCCCTTCGCGCTCGCCCACGCGCTCGACCCATCTGGGCTGGGGCACGCAGCA".
    "CACTCACTCGTTGGCTTTGGGACCCCCCTGTCTCGAAACGCCGACA\n";

my $seq_1 = 
    ">1\n".
    "TGTTGGGGACTTGTTCTCAAATGCTAAGAATTAAGAACAAGGCAACATAAAATGTTAAAT".
    "ATTAAAGCCCTTCGCCCGCCGAAGCATTATTTCCTCAAGGATTTAATGAACTTCGGCGGG".
    "CGAAGGTTAGAAACGATGCAATTACGAAGGTTGAGTCTTCGTAATTGAACTCTCAAAGAT".
    "TATATAAAACAATGCGAAACATGAAACATTAAAGACAAGTAAATTATAAGTAAACGACAT".
    "TATTTTTATATTATGTAAACTTGATGTATCCAAATATTAAATACATTTATACCTCTGCCT".
    "TGGCAAAGAATAATTTCCGAGTGATGCGATTGAAATTACAGGGATGTGTGAACAGTAAAG".
    "GAATACTGTTCACTATTTATAGGCACAGGACACAACCTGTGAGGAATTACAATCATGCCC".
    "CTCATAAAAGTTTACAACATTGACTCAGACCTTTATGGGCTAAAAAGTCATTCTATCTTT".
    "AAGTCGGTTCGCCCCTTCATCTTCGGATATGTTGCAATACCGAAGCTTCATGAATGGTGC".
    "CTTCGGCGTCACGTATGAGCAGCTTCAGCCGAAGCTGTTTCTTTCTACAGGACCTTCGGC".
    "GACGAAGCATGGTCCCAACA\n";

my $seq_2=
    ">2\n".
    "TGTCGGGGACCATAATTAGGGGTACCCTCAAGACGCCTAATTCTCAGTTGGTAACCCCCA".
    "TCAGCATAAAGCTGCAAAGGCCTGATGGGTACGATTAAGTCAGGGATCAGTCCACACGAG".
    "TGACTCGATCACGCTTCACCCGAGCCTAGCCTCGGCCAAGGGCAGCCGACCTCGAGAGAC".
    "TTCCGTCTCGCCCGAGGCCCCCCTTTTTACGGCGGACACATCACCGGCTCGCCCGAGGCC".
    "TTGGCTTCGCTCAGAAGCGACCCTGACTAAATCGCCACACCGACTGACCGAGTTGCAGGA".
    "GCATTTAACGCAAAGAGTGAGTCAGACATACAGTCAGGCCTTGCCAAAGGCGCCACGGCG".
    "AACTCCGCTCCGCCCGACCCCAGGGCTCGGACTCGGGCTAAGACCCGGAAGACGGCGAAC".
    "TCCGCTCCGCCCGACCCCAGGGCTCGGCCTCGGGCTAAGACCCGGAAGACGGCGAACTTC".
    "GCTCCGCCCGACCCCAGGGCTCGGACTCGGGCTAAGACCCGGAAGACGGCGAACTCCGCT".
    "CCGCCCGACCCCAGGGCTCGGACTCGGGCTAAGACCCGGAAGACGGCGAACTCCGCTCCG".
    "CCCGACCCCAGGGCTCGGACTCGGGCTAAGACCCGGAAGACGGCGAACTCCGCTCCGCCC".
    "GACCCCAGGGCTCGGACTCGGGCTAAGACCCGGAAGACGGCGAACTCCGCTCCGCCCGAC".
    "CCCAGGGCTCGGACTCGGGCTAAGACCCGGAAGACGACGAAACTCCGCCTCGCCCGACCC".
    "CAGGGCTCGGACTCCGCCCTGGCCTCGGCCAAACGACCTCCGCCTCGCCCGACCCCATGG".
    "CTCGGACTCGGCCTCGGCAACAGAAGACAGACTCAACCTCGGCTTCGGAGGAGCCCCCAC".
    "GTCACCTCGCCTAGGGCACAGACCCGCCACGTCAACAGGAAGCGTCATCATCGTCCTACC".
    "CCGAATCGACTCGGGTCACGGAGAACAAGACCGGCGTCCCATCCGGCCAGCTCCGCCTGA".
    "TGGGCAATGATGGCGCTCCACAAGCTCTGTGACGACGGCGGCCCCCAGCTCTCTTACGGA".
    "AGCAGGGCGACGTCAGCAAGGACTCGACCGCTCCAACAGCTGTCCCTCCGCCAGGCTCCG".
    "TCGCACCTCCGACAGCCACGACATCACGCCAGCAAGGTGCCAAGACCTCTCCGGCTGCCA".
    "CATTGGCATGTACCTAGGGCGCTAGCTCTCTCTCCGCTAGACACGTAGCACTCTGCTACA".
    "CCCCCCATTGTACACCTGGATCCTCTCCTTACGACTATAAAAGGGAGGACCAGGGCCTTC".
    "TTAGAGAAGGTTGGCCGCGCGGGACCGAGGACGGGACAGGCACTCTCTTGGGGCCGCTCG".
    "CTTCCCTCACCCGCGTGGACGCTTGTAACCCCCCTACTGCAATCGCACCCGACCTGGGCG".
    "CGGGACGAACACGAAGGCCGCGGGACTTCCACCTCTCTCACGCTAGACTCCGGCCACCTC".
    "GCCTCTCCCCCCTTCGCGCTCGCCCACGCGCTCGACCCATCTGGGCTGGGGCACGCAGCA".
    "CACTCACTCGTTGGCTTTGGGACCCCCCTGTCTCGAAACGCCGACA\n";
my $program = "fasta34";


#print STDIN "$seq_query\n";

#-----------------------------+
# The following does not work
#-----------------------------+
#my $cmd = "$program -B -m 9 -H -Q";
#open (FASTAPROG , "| $cmd") ||
#    die "Can not open pipe to the FASTA Program\n";
#print FASTAPROG "$seq_query";
#close FASTAPROG;

#-----------------------------+
# The following does not work
#-----------------------------+
#my $cmd = "$program - - -B -m 9 -H -Q";
#open (FASTAPROG , "| $cmd") ||
#    die "Can not open pipe to the FASTA Program\n";
#print FASTAPROG "$seq_1";
#print FASTAPROG "$seq_2";
#close FASTAPROG;
#

#-----------------------------+
# The following does not work
#-----------------------------+
#my $cmd = "$program -B -m 9 -H -Q - -";
#system ($cmd);
##print "$seq_1";
##print "$seq_2";

#-----------------------------+
# The following does not work
#-----------------------------+
#print STDIN "$seq_1";
#print STDIN "$seq_2";
#open (FASTAPROG , "$cmd |") ||
#    die "Can not open pipe to the FASTA Program\n";
#close FASTAPROG;


#-----------------------------+
# THE FOLLOWING DOES NOT WORK
#-----------------------------+
#my $cmd = "$program -B -m 9 -H -Q STDIN STDIN";
#open (FASTAPROG , "| $cmd") ||
#    die "Can not open pipe to the FASTA Program\n";
#print FASTAPROG "$seq_query";
#close FASTAPROG;


#-----------------------------+
# THE FOLLOWING DOES NOT WORK
#-----------------------------+
#my $cmd = "$program -B -m 9 -H -Q - -";
#@args = ($cmd, $seq_1, $seq_2);
#system(@args) == 0 ||
#    die "Whut $!";

#-----------------------------+
# THE FOLLOWING DOES NOT WORK
#-----------------------------+
# Removed quiet
#my $cmd = "$program - - -B -m 9 -H";
#open (FASTAPROG , "| $cmd") ||
#    die "Can not open pipe to the FASTA Program\n";
#print FASTAPROG "$seq_1";
#print FASTAPROG "$seq_2";
#close FASTAPROG;



#my $cmd = "$program - - -B -m 9 -H";
#open (FASTAPROG , "| $cmd") ||
#    die "Can not open pipe to the FASTA Program\n";
#print FASTAPROG "$seq_1";
#print FASTAPROG "$seq_2";
#close FASTAPROG;

#-----------------------------------------------------------+
#
# WORKING COPIES OF EXAMPLE CODE
# 02/20/2008
#
#-----------------------------------------------------------+


#-----------------------------+
# THE FOLLOWING DOES WORK     |
#-----------------------------+
#my $program = "prss34";
##my $program = "lalign";
#my $cmd = "$program - - -B -m 9 -H -Q";
#open (FASTAPROG , "| $cmd") ||
#    die "Can not open pipe to the FASTA Program\n";
#print FASTAPROG "$seq_1";
#print FASTAPROG "$seq_2";
#close FASTAPROG;


#-----------------------------+
# THE FOLLOWING DOES WORK     |
#-----------------------------+
# lalign does must be told to do reverse complement, does not do
# both by default
# Trying : 
# -n to use as DNA nucleotide sequence
# -K Limits the number of alignments shown
# -i To compare the reverse complement
# -I To show alignment between idential sequences
# -B To show the z score does not work
my $program = "lalign";
my $max_align="1";
my $cmd = "$program - - -n -K $max_align -I";
open (FASTAPROG , "| $cmd") ||
    die "Can not open pipe to the FASTA Program\n";
print FASTAPROG "$seq_1";
print FASTAPROG "$seq_2";
#print FASTAPROG "$seq_1";
close FASTAPROG;





exit;
